version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: ocstore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - ocnet

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ocstore_php
    volumes:
      - ./public_html:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ocnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ocstore_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - ocnet

networks:
  ocnet:
